[package]
name = "pi_ecs"
version = "0.1.0"
authors = ["suncy <suncy@gmail.com>"]
edition = "2018"

[dependencies]
# slotmap = "1.0"
slotmap = { path = "slotmap"}
fixedbitset = "0.4"
slab = {path="../pi_lib/slab"}
atom = {path="../pi_lib/atom"}
map = {path="../pi_lib/map"}
any = {path="../pi_lib/any"}
listener = {path="../pi_lib/listener"}
hash = {path="../pi_lib/hash"}
time = {path="../pi_lib/time"}
share = {path="../pi_lib/share"}
wy_rng = {path="../pi_lib/wy_rng"}
debug_info = {path="../pi_lib/debug_info"}
graph = {path="../pi_lib/graph"}
async_graph = {path="../pi_lib/async_graph"}
async = {path="../pi_lib/async"}
pi_ecs_macros = { path = "macros"}
paste = "0.1"
lazy_static = "*"
log = "*"
rand = "*"
thiserror = "1.0"
futures = "0.3"




# im = "*"

# [dependencies.web-sys]
# version = "*"
# features = [
# 	"console",
# ]
